### ISSUE TITLE
Failure on multiple clients

### ISSUE THREAD

**Issue by kolesar-andras** [FranP-code/Pomodoro-Timer-with-Clockify-integration#1]
I have two Clockify workspaces. When I select one of them, project list does not load. Another workspace loads fine.

Javascript console shows an error at `ClockifyTaskForm.jsx:135:20`:

```
TypeError: s.clients[e.clientName] is undefined
```

Related code:

```javascript
if (!data.clients) {
    data.clients = {[project.clientName]: [project]}
} else {
    data.clients[project.clientName].push(project)
}
```

Workspace having more than one client causes the bug. Another workspace has only one client.

Code creates only one key in the `data.clients` object, for the first `clientName` in the order of JSON input. Second name cannot be found in this object.

**Comment by FranP-code** [comment]
Hello @kolesar-andras! Thank you for report this bug.

Merged the solution with this branch: https://github.com/FranP-code/Pomodoro-Timer-with-Clockify-integration/pull/2
